### ISSUE TITLE
predictor.py error

### ISSUE THREAD

**Issue by divijkhaitan** [ZhonghuiGu/HEAL#1]
I tried to make predictions on the following protein files taken from pdb. 
https://files.wwpdb.org/pub/pdb/data/structures/divided/structure_factors/rq/r1rq0sf.ent.gz
https://files.wwpdb.org/pub/pdb/data/structures/divided/structure_factors/08/r108lsf.ent.gz. I am getting the same error on both files using biopython version 1.70, 1.80 and 1.81 using the following run command given on the github repository. 
python predictor.py --task mf --device 0 --pdb r1rq0sf.ent --esm1b_model ./esm1b_t33_650M_UR50S.pt --only_pdbch false --prob 0.5.
Here is the error message.
Traceback (most recent call last):
  File "predictor.py", line 63, in <module>
    model = struct[0]
  File "/home/chs.csb/.anaconda3/envs/heal/lib/python3.7/site-packages/Bio/PDB/Entity.py", line 40, in __getitem__
    return self.child_dict[id]
KeyError: 0.
The environment was downloaded as per the provided yml file. 
How could I fix this? Thank you.

**Comment by ZhonghuiGu** [comment]
Hi!
Thank you for using our tool! 
Currently, our model only support the PDB file as input.
I'm not familiar with your file type, but apparently it's not *.pdb. Maybe you need to search the tutorial of Biopython to find out how to read this kind of structural file or convert it into *.pdb. And if Biopython still can not work, you need to find another way to get the residue type and the coordinates of Ca to construct the edges as input.

**Comment by divijkhaitan** [comment]
I looked up the file format online, there is no functional difference between a pdb and an ent file, you can rename and ent file to pdb, as shown here https://biopython.biopython.narkive.com/aoWbBXT3/ent-versus-pdb-files
